In [25]:
from sklearn.datasets import load_iris
data = load_iris()
print(dir(data)) # 查看data所具有的属性或方法
print(data.DESCR) # 查看数据集的简介

import pandas as pd
#直接读到pandas的数据框中
test = pd.DataFrame(data=data.data, columns=data.feature_names)


['DESCR', 'data', 'feature_names', 'target', 'target_names']
Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= =====

In [26]:
test.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### 1. 导入数据集

【知识点：输入和输出】

如何导入存在数字和文本的数据集？

In [61]:
def change_dtype(x):
    return float(x)  

In [167]:
import numpy as np


# 导入数字和文本数据集
datapath = './iris.data'
data = np.genfromtxt(datapath,delimiter=",",dtype='object',names=True,converters={0:change_dtype,1:change_dtype,2:change_dtype,3:change_dtype})

data['sepallength']

array([5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0,
       5.0, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4,
       5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6, 5.3, 5.0, 7.0, 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6.0, 5.7, 5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5.0, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6.0, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6.0, 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9], dtype=object)

In [80]:
data['species']==b'Iris-setosa'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

### 2. 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

【知识点：统计相关】

如何计算numpy数组的均值，中位数，标准差？

In [68]:
# 均值
print("the mean of sepallength:",np.mean(data['sepallength']),)

#中位数
print("the median of sepallength:",np.median(data['sepallength']),)

#标准差
print("the std of sepallength:",np.std(data['sepallength']),)

the mean of sepallength: 5.843333333333335
the median of sepallength: 5.8
the std of sepallength: 0.8253012917851409


### 3. 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）。

【知识点：统计相关】

如何标准化数组？

In [78]:
# 最大最小值初始化
s_max,s_min = np.amax(data['sepallength']), np.amin(data['sepallength'])

new_sepallength = (data['sepallength'] - s_min)/(s_max - s_min)


data['sepallength'] = new_sepallength

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\core\_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)


### 4. 找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

【知识点：统计相关】

如何找到numpy数组的百分位数？

In [69]:
# 5,95的分位数

print("the 5% and 95% pre of sepallength: ", np.percentile(data['sepallength'],[5,95]))

the 5% and 95% pre of sepallength:  [4.6 7.254999999999998]


### 5. 把iris_data数据集中的20个随机位置修改为np.nan值。

【知识点：随机抽样】

如何在数组中的随机位置修改值？

In [70]:
# 随机位置修改

data[20]

(5.4, 3.4, 1.7, 0.2, b'Iris-setosa')

In [73]:
data[20]=np.nan
data[20]

(nan, nan, nan, nan, nan)

### 6. 在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

【知识点：逻辑函数、搜索】

如何在numpy数组中找到缺失值的位置？

### 7. 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

【知识点：搜索】

如何根据两个或多个条件筛选numpy数组？

In [84]:
data[(data['sepallength']<5.0 ) & (data['petallength'] >1.5)]

array([(4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, b'Iris-setosa'),
       (4.9, 2.4, 3.3, 1.0, b'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, b'Iris-virginica')],
      dtype=[('sepallength', 'O'), ('sepalwidth', 'O'), ('petallength', 'O'), ('petalwidth', 'O'), ('species', 'O')])

### 8. 选择没有任何 nan 值的 iris_data行。

【知识点：逻辑函数、搜索】

如何从numpy数组中删除包含缺失值的行？

### 9. 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

【知识点：统计相关】

如何计算numpy数组两列之间的相关系数？

In [109]:
np.corrcoef(data['sepallength'].astype(float),data['petallength'].astype(float))

# 如果没有astype(float) 会出现  np.corrcoef 'float' object has no attribute 'shape' 的问题

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

### 10. 找出iris_data是否有任何缺失值。
【知识点：逻辑函数】

如何查找给定数组是否具有空值？

In [113]:
x = data['sepallength'].astype(float)

np.isnan(x)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

### 11. 在numpy数组中将所有出现的nan替换为0。

【知识点：逻辑函数】

如何在numpy数组中用0替换所有缺失值？

In [115]:
## 方法一，使用逻辑函数 nan_to_num
np.nan_to_num(data)



array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.0, 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5.0, 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5.0, 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.0, 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3.0, 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4.0, 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

### 12. 找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

【知识点：数组操作】

如何在numpy数组中查找唯一值的计数？

In [123]:
s_counts = {}
for s in data['species']:
    s_counts[s]=s_counts.get(s,0)+1

s_counts

{b'Iris-setosa': 50, b'Iris-versicolor': 50, b'Iris-virginica': 50}

### 13. 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 --> ‘small’；3-5 --> ‘medium’；’>=5 --> ‘large’。

【知识点：统计相关】

如何将数字转换为分类（文本）数组？

In [140]:


# 排序
petallength = np.digitize(data['petallength'].astype('float'), [0,3,5,10], right=False)

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}

petallength_map = [label_map[x] for x in petallength]

petallength_map 

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

### 14. 在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3。

【知识点：数组操作】

如何从numpy数组的现有列创建新列？

In [192]:
data['petallength']

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4,
       4.6, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1, 6.0, 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.0, 5.1, 5.3, 5.5,
       6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1], dtype=object)

In [207]:
# 计算新的一列的数值

petallength = data['petallength'].astype('float')
sepallength = data['sepallength'].astype('float')

new_volume = (np.pi * petallength * (sepallength **2))/3

new_volume = new_volume.astype('object')

In [211]:
# 
new_data =  np.column_stack((data,new_volume.T))

In [216]:
new_data[:4,1]

array([38.13265162927291, 35.200498485922445, 30.0723720777127,
       33.238050274980004], dtype=object)

### 15. 随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。

【知识点：随机抽样】

如何在numpy中进行概率抽样？

### 16. 根据 sepallength 列对数据集进行排序。

【知识点：排序】

如何按列对2D数组进行排序？

In [220]:
sort_data = sorted(data,key = lambda x:x[0])

### 17. 在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）。

【知识点：数组操作】

如何在numpy数组中找出出现次数最多的值？

In [223]:
petallength = list( data['petallength'])

In [234]:
petallength_count = {}

for p in petallength :
    petallength_count[p] = petallength_count.get(p,0)+1
    
petallength_count = sorted(petallength_count.items(),key = lambda x:-x[1])
petallength_count[0][0]

1.5

In [238]:

vals, counts = np.unique(data['petallength'], return_counts=True)
print(vals,counts)

np.argmax()

[1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.9 3.0 3.3 3.5 3.6 3.7 3.8 3.9 4.0 4.1
 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9
 6.0 6.1 6.3 6.4 6.6 6.7 6.9] [ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]


### 18. 在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置。

【知识点：搜索】

如何找到第一次出现大于给定值的位置？

In [239]:

np.argwhere(data['petalwidth'].astype(float) > 1.0)[0]


array([50], dtype=int64)