In [1]:
import tensorflow as tf
import numpy as np
import random
# https://www.w3cschool.cn/tensorflow_python/tensorflow_python-le4w2kjm.html # 函数使用介绍网站

# tf.matmul 矩阵相乘

In [13]:
# 1. 矩阵相乘 A_{a*b}\ast B_{b*c}=C_{a*c}

# 根据矩阵相乘的匹配原则，左乘矩阵的列数要等于右乘矩阵的行数。

# 在多维（三维、四维）矩阵的相乘中，需要最后两维满足匹配原则。

# 可以将多维矩阵理解成：（矩阵排列，矩阵），即后两维为矩阵，前面的维度为矩阵的排列。

# 比如对于（2，2，4）来说，视为2个（2，4）矩阵。

# 对于（2，2，2，4）来说，视为2*2个（2，4）矩阵。

In [79]:
a_2d = tf.constant([1.0]*6, shape=[2, 3])
b_2d = tf.constant([2.0]*12, shape=[3, 4])
c_2d = tf.matmul(a_2d, b_2d)
c_2d

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]], dtype=float32)>

In [10]:
a_3d = tf.constant([1]*12, shape=[2, 2, 3]) # 2个 [2,3] 的矩阵
b_3d = tf.constant([2]*24, shape=[2, 3, 4]) # 2个 [3,4] 的矩阵
c_3d = tf.matmul(a_3d, b_3d)
c_3d

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6]]], dtype=int32)>

In [11]:
a_4d = tf.constant([1]*24, shape=[2, 2, 2, 3]) # 2*2个 [2,3] 的矩阵
b_4d = tf.constant([2]*48, shape=[2, 2, 3, 4]) # 2*2个 [3,4] 的矩阵
c_4d = tf.matmul(a_4d, b_4d)
c_4d

<tf.Tensor: shape=(2, 2, 2, 4), dtype=int32, numpy=
array([[[[6, 6, 6, 6],
         [6, 6, 6, 6]],

        [[6, 6, 6, 6],
         [6, 6, 6, 6]]],


       [[[6, 6, 6, 6],
         [6, 6, 6, 6]],

        [[6, 6, 6, 6],
         [6, 6, 6, 6]]]], dtype=int32)>

# reduce_sum 操作

In [2]:
a = tf.constant([1,2,3,4],shape=[2,2])
print(a)
b = tf.constant([1,2,3,4],shape=[2,2])
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
# 默认会消除一个维度
tf.reduce_sum(a,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [5]:
# 可以保持那个维度
tf.reduce_sum(a,axis=1,keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [7]], dtype=int32)>

In [6]:
tf.reduce_sum(a,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 6]], dtype=int32)>

# tf.reduce_mean 操作 

In [122]:
a = tf.reduce_sum([
    [[1,2],[6,0]],
    [[2,1],[3,5]]
]) -  tf.reduce_sum([
    [[1,2],[6,0]],
    [[2,1],[3,0]]
])
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [123]:
a = tf.constant([1,0,1,0])
print(a)
tf.reduce_mean(a)

tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [124]:
a = tf.constant([1.0,0.,1.,0.])
print(a)
tf.reduce_mean(a)

tf.Tensor([1. 0. 1. 0.], shape=(4,), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [10]:
a = tf.constant([1,1,1,1,0,1,2,3.],shape=[2,4])
print(a)
print(tf.reduce_mean(a))
print(tf.reduce_mean(a,axis=-1))
print(tf.reduce_mean(a,axis=0))

tf.Tensor(
[[1. 1. 1. 1.]
 [0. 1. 2. 3.]], shape=(2, 4), dtype=float32)
tf.Tensor(1.25, shape=(), dtype=float32)
tf.Tensor([1.  1.5], shape=(2,), dtype=float32)
tf.Tensor([0.5 1.  1.5 2. ], shape=(4,), dtype=float32)


# tf.square 求平方操作

In [8]:
a = tf.constant([i for i in range(4)],shape=[2,2])
print(a)

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [9]:
tf.square(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [4, 9]], dtype=int32)>

# tf.tensordot 矩阵相乘在相加并消除对应维度操作：相当于指定维度进行矩阵相乘

In [10]:
a = tf.constant([0,1,2,1,3,4,5,2,3,4,5,0],shape=[2,1,3,2])
print(a)
b =tf.constant([1,3,2,3,1,2],shape=[2,3,1])
print(b)

tf.Tensor(
[[[[0 1]
   [2 1]
   [3 4]]]


 [[[5 2]
   [3 4]
   [5 0]]]], shape=(2, 1, 3, 2), dtype=int32)
tf.Tensor(
[[[1]
  [3]
  [2]]

 [[3]
  [1]
  [2]]], shape=(2, 3, 1), dtype=int32)


In [11]:
# 将a的第0维和第2维concat然后打平是1*1*6 =1*6， 将b的前两维concat然后打平是1*6；最后把这四个维度消除掉，最后变为(1,2,1) 
# [0,2,3,5,3,5] 点成 [1,3,2,3,1,2] = 0+6+6+15+3+10 = 40
# [1,1,4,2,4,0] 点成 [1,3,2,3,1,2] = 1+3+8+6+4+0 = 22
res3 = tf.tensordot(a,b,axes=([0,2],[0,1]))
res3

<tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
array([[[40],
        [22]]], dtype=int32)>

In [12]:
# 将a的最后两维concat然后打平是6*1维度 ， 将b的前两维度concat然后打平是6*1； 最后把这四个维度消除掉，然后最后为(2,1,1)
# [0,1,2,1,3,4] 点成 [1,3,2,3,1,2] = 0+3+4+3+3+8 =21
# [5,2,3,4,5,0] 点成 [1,3,2,3,1,2] = 5+6+6+12+5+0 =34
res2 = tf.tensordot(a,b,axes=2)
res2

<tf.Tensor: shape=(2, 1, 1), dtype=int32, numpy=
array([[[21]],

       [[34]]], dtype=int32)>

In [13]:
# 将a的最后一维与b的第一维进行点成对应位置相乘再相加消除掉这两个维度，最终维度变为（2，1，3，3，1）
# 0*1 + 1*3 = 3;0*3 + 1*1=1; 0*2+1*2 = 2; [3],[1],[2]
# 2*1 + 1*3 = 5;2*3+1*1 = 7; 2*2+1*2 = 6; [5],[7],[6] 
res1 = tf.tensordot(a,b,axes=1)
res1

<tf.Tensor: shape=(2, 1, 3, 3, 1), dtype=int32, numpy=
array([[[[[ 3],
          [ 1],
          [ 2]],

         [[ 5],
          [ 7],
          [ 6]],

         [[15],
          [13],
          [14]]]],



       [[[[11],
          [17],
          [14]],

         [[15],
          [13],
          [14]],

         [[ 5],
          [15],
          [10]]]]], dtype=int32)>

# tf.squeeze 消除维度为1的维度

In [3]:
test01 = tf.constant(np.random.randn(5,1))
print(test01)
tf.squeeze(test01,axis=-1)

tf.Tensor(
[[-0.06166652]
 [-0.04255655]
 [-0.77434984]
 [-0.96464352]
 [ 1.16836593]], shape=(5, 1), dtype=float64)


<tf.Tensor: shape=(5,), dtype=float64, numpy=array([-0.06166652, -0.04255655, -0.77434984, -0.96464352,  1.16836593])>

In [25]:
a = tf.constant([i for i in range(4)],shape=[2,1,2,1])
print(a)

tf.Tensor(
[[[[0]
   [1]]]


 [[[2]
   [3]]]], shape=(2, 1, 2, 1), dtype=int32)


In [26]:
# 默认是把所有维度为1的维度消除掉
tf.squeeze(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [29]:
# 消除指定的维度，消除第二维
tf.squeeze(a,axis=1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[0],
        [1]],

       [[2],
        [3]]], dtype=int32)>

In [30]:
# 消除指定的维度，消除最后一维
tf.squeeze(a,axis=-1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[0, 1]],

       [[2, 3]]], dtype=int32)>

# tf.expand_dim 扩维

In [2]:
a = tf.constant([random.randint(0,10) for _ in range(20)],shape=[2,2,5])
print(a)

tf.expand_dims(a,axis=-1)

tf.Tensor(
[[[ 0  5  9  1  4]
  [10  2  4  6  8]]

 [[ 1  5  2  4  7]
  [10  7  9  7  6]]], shape=(2, 2, 5), dtype=int32)


<tf.Tensor: shape=(2, 2, 5, 1), dtype=int32, numpy=
array([[[[ 0],
         [ 5],
         [ 9],
         [ 1],
         [ 4]],

        [[10],
         [ 2],
         [ 4],
         [ 6],
         [ 8]]],


       [[[ 1],
         [ 5],
         [ 2],
         [ 4],
         [ 7]],

        [[10],
         [ 7],
         [ 9],
         [ 7],
         [ 6]]]], dtype=int32)>

In [ ]:
tf.reshape(x,)

# tf.multiply 对应位置相乘，会自扩维

In [6]:
a = tf.constant([random.randint(0,10) for _ in range(4)],shape=[2,2])
b = tf.constant([random.randint(0,10) for _ in range(2)],shape=[1,2])
print(a)
print(b)

tf.Tensor(
[[6 9]
 [1 7]], shape=(2, 2), dtype=int32)
tf.Tensor([[4 9]], shape=(1, 2), dtype=int32)


In [7]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 81],
       [ 4, 63]], dtype=int32)>

# tf.transpose转置操作测试

In [2]:
a = tf.constant([random.randint(0,10) for _ in range(15)],shape=[3,5])
print(a)
print(tf.transpose(a))

tf.Tensor(
[[10  8  9 10  4]
 [ 2  4  2  0  4]
 [ 5  2  1  7  8]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[10  2  5]
 [ 8  4  2]
 [ 9  2  1]
 [10  0  7]
 [ 4  4  8]], shape=(5, 3), dtype=int32)


In [5]:
a = tf.constant([random.randint(0,10) for _ in range(15)], shape=[3,5,1])
print(a)
print(tf.transpose(a,perm=[2,0,1])) # 把原先的第三维变为第一维，第一维变为第二维，第二维变为第三维

tf.Tensor(
[[[ 2]
  [ 9]
  [ 7]
  [ 2]
  [ 0]]

 [[ 0]
  [10]
  [ 0]
  [ 4]
  [ 9]]

 [[ 1]
  [10]
  [ 1]
  [ 5]
  [ 5]]], shape=(3, 5, 1), dtype=int32)
tf.Tensor(
[[[ 2  9  7  2  0]
  [ 0 10  0  4  9]
  [ 1 10  1  5  5]]], shape=(1, 3, 5), dtype=int32)


# tf.linalg.band_part 构建上/下三角矩阵操作
```python
tf.linalg.band_part(
    input,
    num_lower,
    num_upper,
    name=None
)
```
### 作用：主要功能是以对角线为中心，取它的副对角线部分，其他部分用0填充。
### input:输入的张量.
### num_lower:下三角矩阵保留的副对角线数量，从主对角线开始计算，相当于下三角的带宽。取值为负数时，则全部保留。
### num_upper:上三角矩阵保留的副对角线数量，从主对角线开始计算，相当于上三角的带宽。取值为负数时，则全部保留。

In [16]:
a = tf.ones([1, 1, 5, 5])
print("原始矩阵：\n",a,"\n")

b =tf.linalg.band_part(a,0,0)
print("只保留主对角线：\n",b,"\n")

c = tf.linalg.band_part(a,0,-1)
print("只保留对角线以上元素：",c,"\n")

d = tf.linalg.band_part(a,-1,0)
print("只保留对角线一下的元素：",d,"\n")

e = tf.linalg.band_part(a,1,2)
print("对角线一下的保留一行，对角线以上的保留两行：",e,"\n")

f = 1 - tf.linalg.band_part(a,-1,0)
print("可以通过减法实现去除主对角线的矩阵：\n",f,"\n")

原始矩阵：
 tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]], shape=(1, 1, 5, 5), dtype=float32) 

只保留主对角线：
 tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(1, 1, 5, 5), dtype=float32) 

只保留对角线以上元素： tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [0. 1. 1. 1. 1.]
   [0. 0. 1. 1. 1.]
   [0. 0. 0. 1. 1.]
   [0. 0. 0. 0. 1.]]]], shape=(1, 1, 5, 5), dtype=float32) 

只保留对角线一下的元素： tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0.]
   [1. 1. 1. 1. 0.]
   [1. 1. 1. 1. 1.]]]], shape=(1, 1, 5, 5), dtype=float32) 

对角线一下的保留一行，对角线以上的保留两行： tf.Tensor(
[[[[1. 1. 1. 0. 0.]
   [1. 1. 1. 1. 0.]
   [0. 1. 1. 1. 1.]
   [0. 0. 1. 1. 1.]
   [0. 0. 0. 1. 1.]]]], shape=(1, 1, 5, 5), dtype=float32) 

可以通过减法实现去除主对角线的矩阵：
 tf.Tensor(
[[[[0. 1. 1. 1. 1.]
   [0. 0. 1. 1. 1.]
   [0. 0. 0. 1. 1.]
   [0. 0. 0. 0. 1.]
   [0. 0. 0. 0. 0.]]]], shape=(1, 1, 5, 5), dtype=float32) 



# tf.split 把某一维度分割成多个维度

In [18]:
a = tf.constant([random.randint(0,10) for _ in range(20)],shape= [2,2,5])
print(a)

tf.Tensor(
[[[5 6 7 8 9]
  [6 2 0 0 3]]

 [[7 7 1 9 2]
  [3 8 0 1 6]]], shape=(2, 2, 5), dtype=int32)


In [19]:
# 将a的第三维分割成5组
tf.split(a,5,axis=2)

[<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[5],
         [6]],
 
        [[7],
         [3]]], dtype=int32)>, <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[6],
         [2]],
 
        [[7],
         [8]]], dtype=int32)>, <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[7],
         [0]],
 
        [[1],
         [0]]], dtype=int32)>, <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[8],
         [0]],
 
        [[9],
         [1]]], dtype=int32)>, <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[9],
         [3]],
 
        [[2],
         [6]]], dtype=int32)>]

In [24]:
# 将a的第三维分割成5组，然后
tf.concat(tf.split(a,5,axis=2),axis=0)

<tf.Tensor: shape=(10, 2, 1), dtype=int32, numpy=
array([[[5],
        [6]],

       [[7],
        [3]],

       [[6],
        [2]],

       [[7],
        [8]],

       [[7],
        [0]],

       [[1],
        [0]],

       [[8],
        [0]],

       [[9],
        [1]],

       [[9],
        [3]],

       [[2],
        [6]]], dtype=int32)>

# tf.einsum 操作测试,自定义指定维度运算

In [11]:
a = tf.constant(np.random.randn(3,2))
print(a)
b = tf.constant(np.random.randn(2,2,1))
print(b)

tf.Tensor(
[[ 1.44847293  0.69530925]
 [-1.11874498  1.52765233]
 [-0.76490646 -0.05232171]], shape=(3, 2), dtype=float64)
tf.Tensor(
[[[-1.0008997 ]
  [ 1.61986336]]

 [[-0.23082717]
  [ 0.22685664]]], shape=(2, 2, 1), dtype=float64)


In [12]:
tf.einsum('ij,bjk->bik',a,b)

<tf.Tensor: shape=(2, 3, 1), dtype=float64, numpy=
array([[[-0.32347016],
        [ 3.59433954],
        [ 0.68084063]],

       [[-0.17661139],
        [ 0.60479481],
        [ 0.16469167]]])>

In [6]:
tf.nn.relu([-5])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>

# tf.concat 操作测试

In [5]:
a = tf.constant([1],dtype=tf.float32)
b = tf.constant([0.1])
tf.concat([a,b],axis=-1) # dtype必须相同

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1. , 0.1], dtype=float32)>

In [3]:
a = tf.constant([[1],[2]])
b = tf.constant([[1,2],[2,4]])
tf.concat([a,b],axis=-1) # shape处理concat的维度外，其他必须保持一致

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 2],
       [2, 1, 2, 4]], dtype=int32)>

In [8]:
a = tf.constant([[1.,1],[2,2]])
b = tf.constant([[1.,2],[2,4]])
c = tf.concat([a,b],axis=0)
print(c)
tf.reduce_mean(c,axis=0,keepdims=True)

tf.Tensor(
[[1. 1.]
 [2. 2.]
 [1. 2.]
 [2. 4.]], shape=(4, 2), dtype=float32)


<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.5 , 2.25]], dtype=float32)>

# tf.exp 操作测试

In [7]:
a = tf.constant([[-5],[-1.0],[0.0],[1.0],[5]])

In [8]:
tf.exp(a)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[6.7379470e-03],
       [3.6787945e-01],
       [1.0000000e+00],
       [2.7182817e+00],
       [1.4841316e+02]], dtype=float32)>

In [17]:
tf.math.log(tf.constant([[1000.0]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.9077554]], dtype=float32)>

# 15 tf.subtract 操作测试

In [9]:
a = tf.constant([1.0,2,3])
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [10]:
b = tf.constant([2.0,1,3])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 1., 3.], dtype=float32)>

In [11]:
tf.subtract(b,a) # 用b去减去a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1., -1.,  0.], dtype=float32)>

In [14]:
tf.expand_dims(a,axis=-1)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float32)>

In [20]:
a ** 2 / 2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 2. , 4.5], dtype=float32)>

In [19]:
tf.nn.l2_loss(a)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

# tf.keras.layers.Lambda 测试

In [25]:
test = tf.constant([[-5],[-1.0],[0.0],[1.0],[5]])
test

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[-5.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 5.]], dtype=float32)>

In [26]:
tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=-1))(test)

<tf.Tensor: shape=(5, 1, 1), dtype=float32, numpy=
array([[[-5.]],

       [[-1.]],

       [[ 0.]],

       [[ 1.]],

       [[ 5.]]], dtype=float32)>

In [27]:
tf.expand_dims(test, axis=-1)

<tf.Tensor: shape=(5, 1, 1), dtype=float32, numpy=
array([[[-5.]],

       [[-1.]],

       [[ 0.]],

       [[ 1.]],

       [[ 5.]]], dtype=float32)>

In [43]:
expert1 = tf.constant([[1,1,1],[2,2,2]])
expert2 = tf.constant([[2,2,2],[3,3,3]])
expert3 = tf.constant([[3,3,3],[4,4,4]])
experts = [expert1,expert2,expert3]
expert_concat = tf.keras.layers.Lambda(lambda x:tf.stack(x,axis=1))(experts)
expert_concat

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [44]:
tf.stack(experts,axis=1)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [47]:
gate_out = tf.constant([[1,2,3],[2,3,4]])
gate_out = tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=-1))(gate_out)
gate_out

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]], dtype=int32)>

In [48]:
gate_mul_expert = tf.keras.layers.Lambda(lambda x: tf.reduce_sum(x[0] * x[1], axis=1, keepdims=False))(
                [expert_concat, gate_out])
gate_mul_expert

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 14, 14],
       [29, 29, 29]], dtype=int32)>

In [49]:
expert_concat * gate_out

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  1,  1],
        [ 4,  4,  4],
        [ 9,  9,  9]],

       [[ 4,  4,  4],
        [ 9,  9,  9],
        [16, 16, 16]]], dtype=int32)>

In [50]:
tf.reduce_sum(expert_concat*gate_out,axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 14, 14],
       [29, 29, 29]], dtype=int32)>

#  位运算 
TensorFlow支持位操作，在模块tf.bitwise中包含了几个基本的位操作，分别是：
1. bitwise_and() 位与操作 c = a & bc = a & b
2. bitwise_or() 位或操作 c=a|bc=a|b
3. bitwise_xor() 位异或操作 c = (~a & b) | (a & ~b)c = (~a & b) | (a & ~b)
4. invert() 位反操作 c= ac= a
5. left_shift() 位左移操作 c=a<<bc=a<<b
6. right_shift() 位右移操作 c=a>>b


In [76]:
a = tf.constant([0,3,7])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 3, 7], dtype=int32)>

In [77]:
a = tf.bitwise.right_shift(a,2)
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>

In [73]:
a = tf.bitwise.bitwise_and(a,1)
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

# 类型转换

In [80]:
float_data = tf.constant([1,2.0,3])
float_data

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [82]:
#  tf1.0的api
#float->int 
# int_data = tf.to_int32(float_data)
# int_data

#int->float
# float_data = tf.to_float32(int_data)

In [84]:
# 转为int：自动4舍5入
int_data = tf.cast(float_data,tf.int32)
int_data

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [85]:
# 转为更高精度double：
double_data = tf.cast(int_data,tf.float64)
double_data

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

# 字符串切割处理

In [87]:
str_tensor = tf.constant(["1,2,3,4","2,3,4,5"])
str_tensor

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'1,2,3,4', b'2,3,4,5'], dtype=object)>

In [89]:
split_tensor = tf.strings.split(str_tensor,',')
split_tensor

<tf.RaggedTensor [[b'1', b'2', b'3', b'4'], [b'2', b'3', b'4', b'5']]>

In [91]:
split_tensor.shape

TensorShape([2, None])

In [94]:
tf.strings.to_number(split_tensor,tf.int32)

<tf.RaggedTensor [[1, 2, 3, 4], [2, 3, 4, 5]]>

In [95]:
tf.strings.to_number(split_tensor.values,tf.int32)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 2, 3, 4, 5], dtype=int32)>

# tf.SparseTensor 使用

In [108]:
test_sparse_tensor = tf.SparseTensor(indices=[[0,0],[1,2]], # 在对应坐标赋值
                                     values =[1,2],# 上面对应左边的依次赋值的值
                                     dense_shape=[3,4],# 矩阵的shape
                                    )
print(test_sparse_tensor)
tf.sparse.to_dense(test_sparse_tensor) # 把spare

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [106]:
test_sparse_tensor = tf.SparseTensor(indices=[[0,0,0],[1,2,3]], # 在对应坐标赋值
                                     values =[1,2],# 上面对应左边的依次赋值的值
                                     dense_shape=[3,4,5],# 矩阵的shape
                                    )
print(test_sparse_tensor)
tf.sparse.to_dense(test_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0 0]
 [1 2 3]], shape=(2, 3), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4 5], shape=(3,), dtype=int64))


<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [119]:
str_tensor = tf.constant(["1,2","3,4"])
print(str_tensor)
split_tensor = tf.strings.split(str_tensor,',')
print(split_tensor)
print(tf.strings.to_number(split_tensor,tf.int32))
print(tf.strings.to_number(split_tensor.values,tf.int32))
test_sparse_tensor = tf.SparseTensor(indices=[[0,0],[0,1],[1,0],[1,1]], # 在对应坐标赋值
                                     values =tf.strings.to_number(split_tensor.values,tf.int32),# 上面对应左边的依次赋值的值
                                     dense_shape=[2,2],# 矩阵的shape
                                    )
print(test_sparse_tensor)
tf.sparse.to_dense(test_sparse_tensor) # 把spare

tf.Tensor([b'1,2' b'3,4'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'1', b'2'], [b'3', b'4']]>
<tf.RaggedTensor [[1, 2], [3, 4]]>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [1 0]
 [1 1]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 3 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.reduce_mean()

#

In [4]:
a = tf.constant([[1.0],[2],[3]])
a

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float32)>

In [8]:
b = tf.constant([1.0,2,3])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
tf.sigmoid(a)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.7310586 ],
       [0.880797  ],
       [0.95257413]], dtype=float32)>

In [9]:
a * b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]], dtype=float32)>