In [1]:
import tensorflow as tf
import numpy as np

In [3]:

#
a = tf.constant(np.random.rand(2,3,4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=float64, numpy=
array([[[0.77589859, 0.52917142, 0.95082487, 0.45841136],
        [0.29730889, 0.3320536 , 0.31708498, 0.89379449],
        [0.32497447, 0.305022  , 0.87018063, 0.09490095]],

       [[0.55496861, 0.66532849, 0.09951245, 0.03182611],
        [0.17428791, 0.67815571, 0.45786389, 0.27277611],
        [0.72137432, 0.70389899, 0.24448032, 0.51100975]]])>

In [6]:
# 
sum_a = tf.reduce_sum(a,axis=1,keepdims=True)
print(sum_a)
sum_square = tf.square(sum_a)
print(sum_square)

tf.Tensor(
[[[1.39818195 1.16624702 2.13809048 1.4471068 ]]

 [[1.45063085 2.04738319 0.80185666 0.81561197]]], shape=(2, 1, 4), dtype=float64)
tf.Tensor(
[[[1.95491278 1.36013212 4.57143089 2.09411808]]

 [[2.10432985 4.19177793 0.6429741  0.66522288]]], shape=(2, 1, 4), dtype=float64)


In [9]:
# 
square_a = tf.square(a)
print(square_a)

square_sum = tf.reduce_sum(square_a,axis = 1,keepdims=True)
print(square_sum)

tf.Tensor(
[[[0.60201862 0.28002239 0.90406794 0.21014097]
  [0.08839258 0.11025959 0.10054288 0.79886859]
  [0.10560841 0.09303842 0.75721432 0.00900619]]

 [[0.30799016 0.442662   0.00990273 0.0010129 ]
  [0.03037628 0.45989516 0.20963934 0.07440681]
  [0.52038091 0.49547379 0.05977063 0.26113096]]], shape=(2, 3, 4), dtype=float64)
tf.Tensor(
[[[0.79601961 0.48332041 1.76182514 1.01801575]]

 [[0.85874735 1.39803096 0.27931269 0.33655067]]], shape=(2, 1, 4), dtype=float64)


In [10]:
# 
cross = sum_square - square_sum
print(cross)

fm = tf.reduce_sum(cross,axis=2)
print(fm)

tf.Tensor(
[[[1.15889317 0.87681171 2.80960574 1.07610233]]

 [[1.2455825  2.79374697 0.36366141 0.32867221]]], shape=(2, 1, 4), dtype=float64)
tf.Tensor(
[[5.92141295]
 [4.73166309]], shape=(2, 1), dtype=float64)


In [12]:
nl = tf.reduce_sum(cross,axis=1)
nl

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1.15889317, 0.87681171, 2.80960574, 1.07610233],
       [1.2455825 , 2.79374697, 0.36366141, 0.32867221]])>