In [1]:
import numpy as np

In [4]:
# 一列代表一个向量，query向量
Q = np.array([[2,3],
              [1,1]])
Q

array([[2, 3],
       [1, 1]])

In [5]:
# doc的向量
D = np.array([[1,1],
              [2,3]])

In [19]:
np.matmul(Q.T,D)

array([[4, 5],
       [5, 6]])

In [17]:
np.sum(Q**2,axis=0).reshape((len(Q[0]),1))

array([[ 5],
       [10]])

In [25]:
cos_res = np.matmul( Q.T , D )/ np.multiply(np.sqrt(np.sum(Q**2,axis=0)).reshape((len(Q[0]),1)),np.sqrt(np.sum(D**2,axis=0)))
cos_res

array([[0.8       , 0.70710678],
       [0.70710678, 0.6       ]])

In [27]:
# 计算余弦相似度的方法
def cop_cos(Q,D):
    return np.matmul( Q.T , D )/np.sqrt(np.multiply(np.sum(Q**2,axis=0).reshape((len(Q[0]),1)),
                                                     np.sum(D**2,axis=0)))
Q = np.array([[1,2,3],
              [1,1,1]])
D = np.array([[1,1,1],
              [1,2,3]])
cop_cos(Q,D)

array([[1.        , 0.9486833 , 0.89442719],
       [0.9486833 , 0.8       , 0.70710678],
       [0.89442719, 0.70710678, 0.6       ]])