In [1]:
import tensorflow as tf
from deepctr.models import DCN
from utils import check_model ,get_test_data,SAMPLE_SIZE

In [2]:
SAMPLE_SIZE

8

In [3]:
x,y,feature_columns = get_test_data(SAMPLE_SIZE,sparse_feature_num=2,dense_feature_num=2)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [4]:
for feature in feature_columns:
    print(feature)
    print()

VarLenSparseFeat(sparsefeat=SparseFeat(name='weighted_seq', vocabulary_size=2, embedding_dim=4, use_hash=False, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x7fab266fe9d0>, embedding_name='weighted_seq', group_name='default_group', trainable=True), maxlen=3, combiner='mean', length_name='weighted_seq_seq_length', weight_name='weight', weight_norm=True)

SparseFeat(name='sparse_feature_0', vocabulary_size=4, embedding_dim=4, use_hash=False, dtype=tf.int32, embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x7fab266fe990>, embedding_name='sparse_feature_0', group_name='default_group', trainable=True)

SparseFeat(name='sparse_feature_1', vocabulary_size=4, embedding_dim=4, use_hash=False, dtype=tf.int32, embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x7fab26669dd0>, embedding_name='sparse_feature_1', group_name='default_group', trainable=True)

DenseFeat(name='den

In [5]:
for k,v in x.items():
    print(k,v.shape)
    print(v,"\n")
    

weighted_seq (8, 3)
[[0 1 1]
 [1 1 1]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]] 

weight (8, 3, 1)
[[[ 1.37519266]
  [-0.36388082]
  [-0.34646209]]

 [[ 0.28516911]
  [-1.26447789]
  [ 0.55274439]]

 [[-0.86201528]
  [ 1.00475004]
  [-1.04165614]]

 [[-1.1763951 ]
  [-0.60601337]
  [-0.13730861]]

 [[ 0.11634905]
  [ 1.32325309]
  [-1.61226122]]

 [[-0.3684117 ]
  [ 2.36553904]
  [-0.57157019]]

 [[ 0.76470542]
  [ 1.03699919]
  [-1.68019954]]

 [[ 0.6512518 ]
  [ 2.53475028]
  [-1.41337855]]] 

weighted_seq_seq_length (8,)
[1 3 3 3 2 1 2 3] 

sparse_feature_0 (8,)
[0 3 1 3 2 1 3 2] 

sparse_feature_1 (8,)
[2 1 1 3 0 1 0 2] 

dense_feature_0 (8,)
[0.81057986 0.09825242 0.02204388 0.40577347 0.59811899 0.33006407
 0.73206107 0.88976929] 

dense_feature_1 (8,)
[0.2937393  0.95246452 0.52333653 0.35726546 0.55622383 0.50194577
 0.04446147 0.83510924] 

sequence_sum (8, 1)
[[3]
 [4]
 [1]
 [1]
 [4]
 [0]
 [0]
 [2]] 

sequence_mean (8, 4)
[[1 6 2 5]
 [1 1 1 3]
 [5 0 4 1]
 [1 4 2 

In [6]:
y

array([1, 1, 0, 0, 1, 1, 0, 1])

In [7]:
model = DCN(feature_columns,feature_columns,cross_num=1,cross_parameterization='vector',
            dnn_hidden_units=(8,),dnn_dropout=0.5)

CrossNet parameterization: vector


In [8]:
model.compile('adam', 'binary_crossentropy', metrics=['binary_crossentropy'])
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
weighted_seq (InputLayer)       [(None, 3)]          0                                            
__________________________________________________________________________________________________
sparse_seq_emb_weighted_seq (Em (None, 3, 4)         8           weighted_seq[0][0]               
__________________________________________________________________________________________________
weighted_seq_seq_length (InputL [(None, 1)]          0                                            
__________________________________________________________________________________________________
weight (InputLayer)             [(None, 3, 1)]       0                                            
______________________________________________________________________________________________

In [9]:
log_dir = "./logs/fit/"
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [10]:
model.fit(x,y,batch_size=100,epochs=1,validation_split=0.5,callbacks=[tensorboard_callback])

/Users/zhenwuzhou/environment/tf2_py3/lib/python3.7/site-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


1/1 [==============================] - 1s 522ms/step - loss: 4.3683 - binary_crossentropy: 4.3683 - val_loss: 0.8994 - val_binary_crossentropy: 0.8994


In [11]:
!tensorboard --logdir ./logs/fit

W0207 15:05:54.215487 123145565294592 plugin_event_accumulator.py:332] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.2.1 at http://localhost:6006/ (Press CTRL+C to quit)
^C


In [12]:
test_dict = {"a":5}
test_dict

{'a': 5}

In [15]:
list(test_dict.values())

[5]