In [33]:
from sklearn import linear_model
import pandas as pd
import numpy as np
# 导入线性模型和多项式特征构造模块
from sklearn.preprocessing import PolynomialFeatures

In [22]:
size = 10
X1 = np.random.randint(10,100,size)
print(X1)
X2 = np.random.rand(size)
print(X2)

Y = 3*X1 + 2*X2
print(Y)

[65 74 60 23 40 54 89 68 51 84]
[0.39765947 0.69907803 0.20187787 0.6397397  0.49946947 0.19304582
 0.90708979 0.49251924 0.54829239 0.95576409]
[195.79531895 223.39815606 180.40375574  70.2794794  120.99893894
 162.38609164 268.81417958 204.98503848 154.09658478 253.91152818]


In [32]:
trainX = np.concatenate((X1.reshape(-1,1),X2.reshape(-1,1)),axis=1)
trainX

array([[65.        ,  0.39765947],
       [74.        ,  0.69907803],
       [60.        ,  0.20187787],
       [23.        ,  0.6397397 ],
       [40.        ,  0.49946947],
       [54.        ,  0.19304582],
       [89.        ,  0.90708979],
       [68.        ,  0.49251924],
       [51.        ,  0.54829239],
       [84.        ,  0.95576409]])

In [39]:
# degree=2表示建立datasets_X的二 次多项式特征X_poly
poly_reg = PolynomialFeatures(degree=2)
X_poly = poly_reg.fit_transform(trainX)
X_poly

array([[1.00000000e+00, 6.50000000e+01, 3.97659474e-01, 4.22500000e+03,
        2.58478658e+01, 1.58133057e-01],
       [1.00000000e+00, 7.40000000e+01, 6.99078029e-01, 5.47600000e+03,
        5.17317741e+01, 4.88710090e-01],
       [1.00000000e+00, 6.00000000e+01, 2.01877868e-01, 3.60000000e+03,
        1.21126721e+01, 4.07546734e-02],
       [1.00000000e+00, 2.30000000e+01, 6.39739699e-01, 5.29000000e+02,
        1.47140131e+01, 4.09266882e-01],
       [1.00000000e+00, 4.00000000e+01, 4.99469470e-01, 1.60000000e+03,
        1.99787788e+01, 2.49469751e-01],
       [1.00000000e+00, 5.40000000e+01, 1.93045818e-01, 2.91600000e+03,
        1.04244742e+01, 3.72666878e-02],
       [1.00000000e+00, 8.90000000e+01, 9.07089788e-01, 7.92100000e+03,
        8.07309912e+01, 8.22811884e-01],
       [1.00000000e+00, 6.80000000e+01, 4.92519242e-01, 4.62400000e+03,
        3.34913084e+01, 2.42575203e-01],
       [1.00000000e+00, 5.10000000e+01, 5.48292388e-01, 2.60100000e+03,
        2.79629118e+01, 

In [40]:
# 创建线性回归模型
lin_reg_2 = linear_model.LinearRegression()
lin_reg_2.fit(X_poly,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
# 查看回归方程系数
lin_reg_2.coef_

array([ 0.00000000e+00,  3.00000000e+00,  2.00000000e+00,  0.00000000e+00,
       -1.17128529e-14, -3.17610088e-13])

In [43]:
lin_reg_2.predict([[1,2,1,4,2,1]])

array([8.])

In [44]:
# 查看回归方程截距
lin_reg_2.intercept_

2.3305801732931286e-12

In [45]:
lin_reg_2.score(X_poly,Y)

1.0