In [6]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [15]:
X = np.random.randint(10,100,10).reshape(-1,1)
print(X)
scaler = StandardScaler()
print(scaler.fit(X))

[[30]
 [49]
 [74]
 [71]
 [72]
 [49]
 [33]
 [84]
 [59]
 [83]]
StandardScaler(copy=True, with_mean=True, with_std=True)


In [16]:
scaler.mean_

array([60.4])

In [17]:
scaler.transform(X)

array([[-1.63991647],
       [-0.61496868],
       [ 0.73364684],
       [ 0.57181298],
       [ 0.6257576 ],
       [-0.61496868],
       [-1.47808261],
       [ 1.27309305],
       [-0.07552247],
       [ 1.21914843]])

In [19]:
(30 - 60.4) / -1.63991647

18.537529536489135

In [22]:
np.std([[30],[49],[74],[71],[72],[49],[33],[84],[59],[83]])

18.53752950098799