In [20]:
import keras as keras
import numpy as np
from keras2pmml import keras2pmml
from sklearn.preprocessing import StandardScaler

print(keras.__version__)

2.3.1


In [27]:
std = StandardScaler()

trainX = np.array([[1],[2],[3]])
trainX_Scaled = std.fit_transform(trainX)
trainY = np.array([2,4,6])

print(trainX)
print(trainX_Scaled)

[[1]
 [2]
 [3]]
[[-1.22474487]
 [ 0.        ]
 [ 1.22474487]]


In [28]:
model = keras.models.Sequential([
    keras.layers.Dense(8,activation = 'relu',input_shape = (1,)),
    keras.layers.Dense(1)
])
model.summary()
model.compile(loss = 'mse',optimizer = 'sgd')

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 8)                 16        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [29]:
history = model.fit(trainX_Scaled,trainY,epochs=100,steps_per_epoch=3)

Epoch 1/100
3/3 [==============================] - 0s 15ms/step - loss: 20.0373
Epoch 2/100
3/3 [==============================] - 0s 886us/step - loss: 16.4215
Epoch 3/100
3/3 [==============================] - 0s 632us/step - loss: 13.4588
Epoch 4/100
3/3 [==============================] - 0s 634us/step - loss: 10.8498
Epoch 5/100
3/3 [==============================] - 0s 792us/step - loss: 8.5958
Epoch 6/100
3/3 [==============================] - 0s 659us/step - loss: 6.6041
Epoch 7/100
3/3 [==============================] - 0s 676us/step - loss: 4.8345
Epoch 8/100
3/3 [==============================] - 0s 609us/step - loss: 3.3639
Epoch 9/100
3/3 [==============================] - 0s 611us/step - loss: 2.2383
Epoch 10/100
3/3 [==============================] - 0s 647us/step - loss: 1.4494
Epoch 11/100
3/3 [==============================] - 0s 824us/step - loss: 0.9401
Epoch 12/100
3/3 [==============================] - 0s 639us/step - loss: 0.6326
Epoch 13/100
3/3 [================

In [33]:
model.predict(std.transform([[5]]))

array([[10.0709305]], dtype=float32)

In [35]:
model.get_config()

{'name': 'sequential_3',
 'layers': [{'class_name': 'Dense',
   'config': {'name': 'dense_5',
    'trainable': True,
    'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'units': 8,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'VarianceScaling',
     'config': {'scale': 1.0,
      'mode': 'fan_avg',
      'distribution': 'uniform',
      'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_6',
    'trainable': True,
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'VarianceScaling',
     'config': {'scale': 1.0,
      'mode': 'fan_avg',
      'distribution': 'uniform',
      'seed': None}},
    'bias_initializer': {'

In [37]:
layer_activations = map(lambda x: x['config']['activation'], model.get_config())
layer_activations

In [34]:
params = {
    'feature_names':['inputX'],
    'target_values':['outputY'],
    'target_name':'doubleValue',
    'copyright':'Steven Zhou',
    'description':'Simple Test',
    'model_name':'Residual Value Estimate'
}

keras2pmml(estimator = model,transformer=std, file = 'residual_value_estimate.pmml', **params)

[x] Performing model validation.
[x] Model validation successful.
[x] Generating Data Dictionary:
	[-] inputX...OK!


TypeError: string indices must be integers