In [2]:
import tensorflow as tf 
import numpy as np

In [3]:
trainX = np.random.randn(100)
# trainX = trainX.reshape(1,100)
trainY = 2 * trainX + 5
# trainY = trainY.T
trainY.shape

(100,)

In [4]:
trainX

array([ 1.40300092e+00, -1.68604303e+00,  6.49698337e-01,  1.19568318e+00,
        2.90942884e-01, -1.28967469e+00, -9.25438529e-01, -4.25152247e-01,
       -2.02572804e+00,  8.53134695e-01, -8.00676574e-01,  8.55300929e-01,
       -3.65990868e-02,  4.90331784e-01,  3.30915521e-02, -4.64329504e-01,
       -1.82151671e+00, -1.87922542e+00, -4.76519461e-01,  5.90968326e-01,
       -7.37255856e-01,  1.89205807e-02,  1.15868280e+00, -2.06287012e-01,
       -6.39460118e-01, -2.69470478e+00,  1.87942984e+00,  1.38721026e+00,
       -1.07339646e+00, -4.70081492e-01,  8.21284727e-01,  5.43721574e-01,
       -9.49487843e-03,  6.32528077e-01, -4.74348899e-01,  1.49567808e+00,
       -8.03704324e-02,  3.78449624e-01,  1.61412479e+00, -1.84676922e-01,
        1.63935958e-01,  4.07326333e-01,  8.69104514e-01, -2.53600388e-01,
        1.19502781e+00,  5.27663047e-01,  3.72577731e-01, -1.47784124e-01,
        8.54169616e-01, -2.89419884e-01, -1.29782980e-01, -1.28404822e+00,
        1.85137617e+00,  

In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1,input_shape=(1,))
])
optimizer = tf.keras.optimizers.Adam(0.1)
model.compile(optimizer,loss='mse')

history = model.fit(trainX,trainY,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 32.1316
Epoch 2/100
4/4 [==============================] - 0s 822us/step - loss: 26.5080
Epoch 3/100
4/4 [==============================] - 0s 999us/step - loss: 21.6153
Epoch 4/100
4/4 [==============================] - 0s 927us/step - loss: 17.2457
Epoch 5/100
4/4 [==============================] - 0s 812us/step - loss: 13.5420
Epoch 6/100
4/4 [==============================] - 0s 838us/step - loss: 10.3369
Epoch 7/100
4/4 [==============================] - 0s 778us/step - loss: 7.7340
Epoch 8/100
4/4 [==============================] - 0s 777us/step - loss: 5.7728
Epoch 9/100
4/4 [==============================] - 0s 815us/step - loss: 4.2262
Epoch 10/100
4/4 [==============================] - 0s 829us/step - loss: 3.0229
Epoch 11/100
4/4 [==============================] - 0s 838us/step - loss: 2.1083
Epoch 12/100
4/4 [==============================] - 0s 734us/step - loss: 1.4385
Epoch 13/100
4/4 [===============

4/4 [==============================] - 0s 778us/step - loss: 9.0286e-13
Epoch 99/100
4/4 [==============================] - 0s 704us/step - loss: 9.0286e-13
Epoch 100/100
4/4 [==============================] - 0s 860us/step - loss: 9.0286e-13


In [5]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[2.000005]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([4.9999523], dtype=float32)>]

In [13]:
model.predict([5])

array([[15.000001]], dtype=float32)

In [14]:
model.save("aaa.model")

INFO:tensorflow:Assets written to: aaa.model/assets


In [15]:
new_model = tf.keras.models.load_model("aaa.model")

In [16]:
testX = np.array([5.])
testX

array([5.])

In [17]:
new_model.predict(testX)

array([[15.000001]], dtype=float32)

In [7]:
#保存模型
tf.saved_model.save(model,"testModel/v1")

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: testModel/v1/assets


In [8]:
# 模型加载
test_model = tf.saved_model.load("testModel/v1")

In [9]:
trainX[0:10]

array([ 1.40300092, -1.68604303,  0.64969834,  1.19568318,  0.29094288,
       -1.28967469, -0.92543853, -0.42515225, -2.02572804,  0.85313469])

In [12]:
test_model(trainX)

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * Tensor("inputs:0", shape=(100,), dtype=float64)
    * False
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='dense_1_input')
    * True
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='inputs')
    * True
    * None
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='dense_1_input')
    * False
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='inputs')
    * False
    * None
  Keyword arguments: {}