In [1]:
import tensorflow as tf
import numpy as np

In [2]:
f1_list = np.array([np.random.randint(1,100) for _ in range(100)])
print(f1_list)
print()
f2_list = np.array([np.random.randint(1,100) for _ in range(100)])
print(f2_list)
print()
label = f1_list + f2_list * 2
print(label)

[33 31 88 67 40 63 84 98 94 41 49 81 76 56 68  4 61 84 78  3 10 91 23 17
 48 36 24 18  4 52 31 31 72 26 60 38 48 57 74 11 43 26 44 48  7 43 89 79
 10  8 65 12 50 50 36 14 65 38 24 17 73 15 76 43 48 98 14 91 28 39  8 40
 25  8 94 30 47 74 74 51 56 49 92 31 24 99 21 64  2 77 84  3  7 63 79 18
 46 13  2 69]

[12 69 58 74 25 94 75 79 79 21  1 23 87 49 16 58 81  7 21 25 67 23 13 44
 48 84 74 38 75 63 17 51 53 24 86 91 52 73 50 53 65 24 99 69  8 76 65  1
  1  2 45 51 15 21 64 46 98 39 98 20 71 84 14 22 13 19 79  2 57  7 83 36
 60 79 68 55 50 32  2 94 72  7 29 90 52 11 78 88 38 14 51  3 26 12 40 86
 16 57 27 81]

[ 57 169 204 215  90 251 234 256 252  83  51 127 250 154 100 120 223  98
 120  53 144 137  49 105 144 204 172  94 154 178  65 133 178  74 232 220
 152 203 174 117 173  74 242 186  23 195 219  81  12  12 155 114  80  92
 164 106 261 116 220  57 215 183 104  87  74 136 172  95 142  53 174 112
 145 166 230 140 147 138  78 239 200  63 150 211 128 121 177 240  78 105
 186   9  59  87 159 

In [3]:
f1_input_layer = tf.keras.layers.Input(shape=(),name='f1_input')
flattened_f1_layer = tf.keras.layers.Flatten()(f1_input_layer)

f2_input_layer = tf.keras.layers.Input(shape=(),name='f2_input')
flattend_f2_layer = tf.keras.layers.Flatten()(f2_input_layer)

concatenate_layer = tf.keras.layers.concatenate([flattened_f1_layer,
                                                 flattend_f2_layer],
                                                axis=-1)
hidden_layer1 = tf.keras.layers.Dense(8,activation='relu')(concatenate_layer)
ouput_layer = tf.keras.layers.Dense(1)(hidden_layer1)

model = tf.keras.models.Model(inputs=[f1_input_layer,f2_input_layer],
                              outputs=ouput_layer)

model.compile(optimizer=tf.keras.optimizers.Adam(),loss='mse')
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
f1_input (InputLayer)           [(None,)]            0                                            
__________________________________________________________________________________________________
f2_input (InputLayer)           [(None,)]            0                                            
__________________________________________________________________________________________________
flatten (Flatten)               (None, 1)            0           f1_input[0][0]                   
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 1)            0           f2_input[0][0]                   
______________________________________________________________________________________________

In [4]:
history = model.fit({"f1_input":f1_list,
                     "f2_input":f2_list},
                    label,batch_size=32,epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 981us/step - loss: 25656.0117
Epoch 2/1000
4/4 [==============================] - 0s 984us/step - loss: 25371.2246
Epoch 3/1000
4/4 [==============================] - 0s 838us/step - loss: 25086.2422
Epoch 4/1000
4/4 [==============================] - 0s 1ms/step - loss: 24802.9355
Epoch 5/1000
4/4 [==============================] - 0s 866us/step - loss: 24526.4668
Epoch 6/1000
4/4 [==============================] - 0s 932us/step - loss: 24250.0000
Epoch 7/1000
4/4 [==============================] - 0s 941us/step - loss: 23965.9434
Epoch 8/1000
4/4 [==============================] - 0s 1ms/step - loss: 23688.7070
Epoch 9/1000
4/4 [==============================] - 0s 1ms/step - loss: 23393.9551
Epoch 10/1000
4/4 [==============================] - 0s 1ms/step - loss: 23112.0195
Epoch 11/1000
4/4 [==============================] - 0s 939us/step - loss: 22822.2949
Epoch 12/1000
4/4 [==============================] - 0s 954us/step - lo

4/4 [==============================] - 0s 1ms/step - loss: 1636.0764
Epoch 98/1000
4/4 [==============================] - 0s 733us/step - loss: 1581.1094
Epoch 99/1000
4/4 [==============================] - 0s 780us/step - loss: 1525.6678
Epoch 100/1000
4/4 [==============================] - 0s 885us/step - loss: 1471.4692
Epoch 101/1000
4/4 [==============================] - 0s 921us/step - loss: 1422.4912
Epoch 102/1000
4/4 [==============================] - 0s 764us/step - loss: 1378.4634
Epoch 103/1000
4/4 [==============================] - 0s 979us/step - loss: 1336.9806
Epoch 104/1000
4/4 [==============================] - 0s 750us/step - loss: 1295.0372
Epoch 105/1000
4/4 [==============================] - 0s 1ms/step - loss: 1255.9871
Epoch 106/1000
4/4 [==============================] - 0s 774us/step - loss: 1221.7976
Epoch 107/1000
4/4 [==============================] - 0s 821us/step - loss: 1185.6130
Epoch 108/1000
4/4 [==============================] - 0s 764us/step - loss:

4/4 [==============================] - 0s 703us/step - loss: 99.8372
Epoch 194/1000
4/4 [==============================] - 0s 889us/step - loss: 96.0049
Epoch 195/1000
4/4 [==============================] - 0s 767us/step - loss: 92.2044
Epoch 196/1000
4/4 [==============================] - 0s 808us/step - loss: 88.4870
Epoch 197/1000
4/4 [==============================] - 0s 900us/step - loss: 85.0217
Epoch 198/1000
4/4 [==============================] - 0s 833us/step - loss: 81.7293
Epoch 199/1000
4/4 [==============================] - 0s 931us/step - loss: 78.5614
Epoch 200/1000
4/4 [==============================] - 0s 848us/step - loss: 75.5804
Epoch 201/1000
4/4 [==============================] - 0s 668us/step - loss: 72.8857
Epoch 202/1000
4/4 [==============================] - 0s 722us/step - loss: 70.3263
Epoch 203/1000
4/4 [==============================] - 0s 739us/step - loss: 67.8098
Epoch 204/1000
4/4 [==============================] - 0s 804us/step - loss: 65.4723
Epoch 2

4/4 [==============================] - 0s 728us/step - loss: 7.7147
Epoch 292/1000
4/4 [==============================] - 0s 820us/step - loss: 7.5973
Epoch 293/1000
4/4 [==============================] - 0s 688us/step - loss: 7.4964
Epoch 294/1000
4/4 [==============================] - 0s 724us/step - loss: 7.3778
Epoch 295/1000
4/4 [==============================] - 0s 837us/step - loss: 7.2686
Epoch 296/1000
4/4 [==============================] - 0s 757us/step - loss: 7.1579
Epoch 297/1000
4/4 [==============================] - 0s 905us/step - loss: 7.0454
Epoch 298/1000
4/4 [==============================] - 0s 882us/step - loss: 6.9429
Epoch 299/1000
4/4 [==============================] - 0s 814us/step - loss: 6.7955
Epoch 300/1000
4/4 [==============================] - 0s 1ms/step - loss: 6.6708
Epoch 301/1000
4/4 [==============================] - 0s 773us/step - loss: 6.5751
Epoch 302/1000
4/4 [==============================] - 0s 700us/step - loss: 6.4414
Epoch 303/1000
4/4 [=

4/4 [==============================] - 0s 727us/step - loss: 1.8842
Epoch 391/1000
4/4 [==============================] - 0s 820us/step - loss: 1.8667
Epoch 392/1000
4/4 [==============================] - 0s 827us/step - loss: 1.8605
Epoch 393/1000
4/4 [==============================] - 0s 791us/step - loss: 1.8386
Epoch 394/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.8200
Epoch 395/1000
4/4 [==============================] - 0s 877us/step - loss: 1.8000
Epoch 396/1000
4/4 [==============================] - 0s 732us/step - loss: 1.7835
Epoch 397/1000
4/4 [==============================] - 0s 706us/step - loss: 1.7709
Epoch 398/1000
4/4 [==============================] - 0s 780us/step - loss: 1.7548
Epoch 399/1000
4/4 [==============================] - 0s 684us/step - loss: 1.7367
Epoch 400/1000
4/4 [==============================] - 0s 683us/step - loss: 1.7186
Epoch 401/1000
4/4 [==============================] - 0s 752us/step - loss: 1.7036
Epoch 402/1000
4/4 [=

4/4 [==============================] - 0s 784us/step - loss: 0.7790
Epoch 490/1000
4/4 [==============================] - 0s 759us/step - loss: 0.7726
Epoch 491/1000
4/4 [==============================] - 0s 862us/step - loss: 0.7673
Epoch 492/1000
4/4 [==============================] - 0s 695us/step - loss: 0.7633
Epoch 493/1000
4/4 [==============================] - 0s 721us/step - loss: 0.7553
Epoch 494/1000
4/4 [==============================] - 0s 866us/step - loss: 0.7540
Epoch 495/1000
4/4 [==============================] - 0s 763us/step - loss: 0.7478
Epoch 496/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.7423
Epoch 497/1000
4/4 [==============================] - 0s 771us/step - loss: 0.7347
Epoch 498/1000
4/4 [==============================] - 0s 781us/step - loss: 0.7280
Epoch 499/1000
4/4 [==============================] - 0s 941us/step - loss: 0.7229
Epoch 500/1000
4/4 [==============================] - 0s 787us/step - loss: 0.7176
Epoch 501/1000
4/4 [=

4/4 [==============================] - 0s 1ms/step - loss: 0.4279
Epoch 589/1000
4/4 [==============================] - 0s 850us/step - loss: 0.4276
Epoch 590/1000
4/4 [==============================] - 0s 732us/step - loss: 0.4249
Epoch 591/1000
4/4 [==============================] - 0s 718us/step - loss: 0.4222
Epoch 592/1000
4/4 [==============================] - 0s 870us/step - loss: 0.4233
Epoch 593/1000
4/4 [==============================] - 0s 725us/step - loss: 0.4241
Epoch 594/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.4221
Epoch 595/1000
4/4 [==============================] - 0s 950us/step - loss: 0.4166
Epoch 596/1000
4/4 [==============================] - 0s 697us/step - loss: 0.4146
Epoch 597/1000
4/4 [==============================] - 0s 790us/step - loss: 0.4135
Epoch 598/1000
4/4 [==============================] - 0s 818us/step - loss: 0.4126
Epoch 599/1000
4/4 [==============================] - 0s 711us/step - loss: 0.4106
Epoch 600/1000
4/4 [===

4/4 [==============================] - 0s 826us/step - loss: 0.3114
Epoch 688/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.3073
Epoch 689/1000
4/4 [==============================] - 0s 755us/step - loss: 0.3052
Epoch 690/1000
4/4 [==============================] - 0s 768us/step - loss: 0.3067
Epoch 691/1000
4/4 [==============================] - 0s 718us/step - loss: 0.3044
Epoch 692/1000
4/4 [==============================] - 0s 712us/step - loss: 0.3013
Epoch 693/1000
4/4 [==============================] - 0s 673us/step - loss: 0.2995
Epoch 694/1000
4/4 [==============================] - 0s 809us/step - loss: 0.3007
Epoch 695/1000
4/4 [==============================] - 0s 945us/step - loss: 0.3016
Epoch 696/1000
4/4 [==============================] - 0s 725us/step - loss: 0.2987
Epoch 697/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2960
Epoch 698/1000
4/4 [==============================] - 0s 883us/step - loss: 0.2943
Epoch 699/1000
4/4 [===

4/4 [==============================] - 0s 736us/step - loss: 0.2200
Epoch 787/1000
4/4 [==============================] - 0s 826us/step - loss: 0.2170
Epoch 788/1000
4/4 [==============================] - 0s 755us/step - loss: 0.2181
Epoch 789/1000
4/4 [==============================] - 0s 734us/step - loss: 0.2184
Epoch 790/1000
4/4 [==============================] - 0s 891us/step - loss: 0.2160
Epoch 791/1000
4/4 [==============================] - 0s 833us/step - loss: 0.2170
Epoch 792/1000
4/4 [==============================] - 0s 862us/step - loss: 0.2132
Epoch 793/1000
4/4 [==============================] - 0s 665us/step - loss: 0.2167
Epoch 794/1000
4/4 [==============================] - 0s 710us/step - loss: 0.2294
Epoch 795/1000
4/4 [==============================] - 0s 949us/step - loss: 0.2259
Epoch 796/1000
4/4 [==============================] - 0s 750us/step - loss: 0.2168
Epoch 797/1000
4/4 [==============================] - 0s 722us/step - loss: 0.2144
Epoch 798/1000
4/4 

4/4 [==============================] - 0s 847us/step - loss: 0.1526
Epoch 886/1000
4/4 [==============================] - 0s 751us/step - loss: 0.1535
Epoch 887/1000
4/4 [==============================] - 0s 872us/step - loss: 0.1520
Epoch 888/1000
4/4 [==============================] - 0s 675us/step - loss: 0.1525
Epoch 889/1000
4/4 [==============================] - 0s 668us/step - loss: 0.1515
Epoch 890/1000
4/4 [==============================] - 0s 890us/step - loss: 0.1508
Epoch 891/1000
4/4 [==============================] - 0s 702us/step - loss: 0.1491
Epoch 892/1000
4/4 [==============================] - 0s 854us/step - loss: 0.1500
Epoch 893/1000
4/4 [==============================] - 0s 758us/step - loss: 0.1489
Epoch 894/1000
4/4 [==============================] - 0s 780us/step - loss: 0.1485
Epoch 895/1000
4/4 [==============================] - 0s 698us/step - loss: 0.1479
Epoch 896/1000
4/4 [==============================] - 0s 836us/step - loss: 0.1465
Epoch 897/1000
4/4 

4/4 [==============================] - 0s 946us/step - loss: 0.1003
Epoch 985/1000
4/4 [==============================] - 0s 865us/step - loss: 0.1000
Epoch 986/1000
4/4 [==============================] - 0s 962us/step - loss: 0.0996
Epoch 987/1000
4/4 [==============================] - 0s 964us/step - loss: 0.0994
Epoch 988/1000
4/4 [==============================] - 0s 744us/step - loss: 0.0983
Epoch 989/1000
4/4 [==============================] - 0s 931us/step - loss: 0.0991
Epoch 990/1000
4/4 [==============================] - 0s 1000us/step - loss: 0.0990
Epoch 991/1000
4/4 [==============================] - 0s 792us/step - loss: 0.0972
Epoch 992/1000
4/4 [==============================] - 0s 968us/step - loss: 0.0965
Epoch 993/1000
4/4 [==============================] - 0s 775us/step - loss: 0.0966
Epoch 994/1000
4/4 [==============================] - 0s 690us/step - loss: 0.0961
Epoch 995/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0953
Epoch 996/1000
4/4 [

In [5]:
model.predict({"f2_input":np.array([5]),
               "f1_input":np.array([3])})

array([[13.720072]], dtype=float32)

In [6]:
model.predict([np.array([5]),
               np.array([3])
              ])

array([[11.715666]], dtype=float32)

In [7]:
model.predict([np.array([3]),
               np.array([5])
              ])

array([[13.720072]], dtype=float32)