【习题1】

只保留打印数组3位小数点

In [4]:
import numpy as np

array = np.random.random([5,3])

np.set_printoptions(precision=8)
print('before', array)


#
np.set_printoptions(precision=3)

print("after",array)

before [[0.12827901 0.67582714 0.96701829]
 [0.8549903  0.97073828 0.46372135]
 [0.99988231 0.73839575 0.09058879]
 [0.99240615 0.92504191 0.64362416]
 [0.43582237 0.8537921  0.06697956]]
after [[0.128 0.676 0.967]
 [0.855 0.971 0.464]
 [1.    0.738 0.091]
 [0.992 0.925 0.644]
 [0.436 0.854 0.067]]


【习题2】

打印限制为6个元素

In [5]:
x = np.linspace(0,10)
print('b',x)

#
np.set_printoptions(threshold=6)
print('a',x)

b [ 0.     0.204  0.408  0.612  0.816  1.02   1.224  1.429  1.633  1.837
  2.041  2.245  2.449  2.653  2.857  3.061  3.265  3.469  3.673  3.878
  4.082  4.286  4.49   4.694  4.898  5.102  5.306  5.51   5.714  5.918
  6.122  6.327  6.531  6.735  6.939  7.143  7.347  7.551  7.755  7.959
  8.163  8.367  8.571  8.776  8.98   9.184  9.388  9.592  9.796 10.   ]
a [ 0.     0.204  0.408 ...  9.592  9.796 10.   ]


In [ ]:
【习题2】

打印完整的数组

In [7]:
np.set_printoptions(threshold=np.iinfo(int).max)
print(x)

[ 0.     0.204  0.408  0.612  0.816  1.02   1.224  1.429  1.633  1.837
  2.041  2.245  2.449  2.653  2.857  3.061  3.265  3.469  3.673  3.878
  4.082  4.286  4.49   4.694  4.898  5.102  5.306  5.51   5.714  5.918
  6.122  6.327  6.531  6.735  6.939  7.143  7.347  7.551  7.755  7.959
  8.163  8.367  8.571  8.776  8.98   9.184  9.388  9.592  9.796 10.   ]
