## 12.线性代数

### 12.1矩阵乘法

### 12.2矩阵特征值和特征向量

### 12.3 矩阵分解

* 奇异值分解

* QR分解

* Cholesky分解

### 12.4 范数和其他数字

* 矩阵范数

* 矩阵行列式

* 矩阵的秩

* 矩阵的迹

### 12.5 解方程和逆矩阵

* 逆矩阵（inverse matrix）

* 求解线性方程组

### 12.1 矩阵的点积


numpy.dot(a, b[, out]) 计算矩阵的乘积，一维数组计算内积

矩阵除了点积（内积）之外，还有相同大小的两个矩阵的 元素积


In [2]:
# 一维数组计算内积
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
z = np.dot(x, y)
print(z)

70


In [3]:
# 多维数组的乘积

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("x",x,)
print("y",y,)
print("np.dot(x,y)",np.dot(x,y),)
print("np.dot(y,x)",np.dot(y,x),)

x [[1 2]
 [3 4]]
y [[5 6]
 [7 8]]
np.dot(x,y) [[19 22]
 [43 50]]
np.dot(y,x) [[23 34]
 [31 46]]


In [4]:
# 矩阵的元素积

x*y

array([[ 5, 12],
       [21, 32]])

In [8]:
# 矩阵的元素积存在 广播机制 但前提是其中一个数组可以通过广播的方式扩展到第二个数组的size

x = np.array([[2]])
y = np.array([[5,6],[7,8]])
x*y

array([[10, 12],
       [14, 16]])

### 12.5 解方程和逆矩阵

** 逆矩阵

假设矩阵A的逆矩阵为B，则AB = BA =E

numpy.linalg.inv(a)

In [13]:
a = np.array([[1,2,3],[3,2,1],[1,0,-1]])

np.linalg.inv(a)

array([[-2.25179981e+15,  2.25179981e+15, -4.50359963e+15],
       [ 4.50359963e+15, -4.50359963e+15,  9.00719925e+15],
       [-2.25179981e+15,  2.25179981e+15, -4.50359963e+15]])

** 求解线性方程

AX = B

求解X

numpy.linalg.solve(a, b)


In [15]:
#  x + 2y +  z = 7
# 2x -  y + 3z = 7
# 3x +  y + 2z =18

A = np.array([[1,2,1],[2,-1,3],[3,1,2]])
B = np.array([7,7,18])

np.linalg.solve(A,B)

array([ 7.,  1., -2.])