In [1]:
import tensorflow as tf
from tensorflow import keras

import pandas as pd
import numpy as np

pd.set_option("display.max_columns",100)
pd.set_option("display.max_rows",100)

In [3]:
inputs = tf.random.normal([8, 10, 8])
inputs

<tf.Tensor: shape=(8, 10, 8), dtype=float32, numpy=
array([[[ 4.45418060e-01, -1.17736435e+00, -9.48556125e-01,
         -3.55123281e-01,  1.00651944e+00,  2.42546082e-01,
         -1.02531016e-01,  7.12412238e-01],
        [ 7.01276064e-02,  9.20678675e-01, -4.45045829e-01,
          1.08165431e+00,  9.01163101e-01, -9.13057625e-02,
         -9.99122918e-01, -1.12123263e+00],
        [-1.71931013e-01, -6.71896517e-01, -8.43447566e-01,
         -3.24253172e-01, -1.32383358e+00, -2.57345319e-01,
          1.12139142e+00,  7.79971957e-01],
        [ 3.05060089e-01, -3.09870720e+00, -1.83170900e-01,
          2.98976809e-01, -6.86136305e-01, -4.81276810e-01,
          1.13941789e+00, -1.41379142e+00],
        [ 9.60925758e-01,  2.85700470e-01, -1.10150076e-01,
         -1.45311132e-01, -6.06307387e-01, -7.16978610e-01,
         -1.16137075e+00,  1.23391056e+00],
        [-2.69628167e-01, -3.72485340e-01,  1.33170402e+00,
         -7.53780365e-01,  8.87510598e-01,  1.87639987e+00,
        

In [4]:
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)

(8, 4)


In [5]:
output

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[-0.31899425,  0.30926502, -0.08209968,  0.33047837],
       [-0.16262679,  0.20954084, -0.06122895, -0.16393049],
       [ 0.04288912,  0.45246097, -0.01805603,  0.20090318],
       [-0.52608293,  0.26277834,  0.0101213 ,  0.26709598],
       [-0.21658303, -0.11279203, -0.0878709 , -0.01480215],
       [ 0.08478312, -0.22182226,  0.37031913,  0.12969558],
       [-0.05467191,  0.11418501,  0.19461958, -0.13201118],
       [-0.2636222 , -0.06033308,  0.06575197, -0.03976291]],
      dtype=float32)>

In [6]:
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
whole_seq_output

<tf.Tensor: shape=(8, 10, 4), dtype=float32, numpy=
array([[[-9.94469598e-02, -3.84742320e-02, -5.24695478e-02,
          6.33827597e-02],
        [-5.23579232e-02, -3.07595015e-01, -2.61938095e-01,
          1.90988898e-01],
        [-1.09428816e-01, -9.81648713e-02, -8.98980945e-02,
          1.82678755e-02],
        [-2.64702141e-01, -1.77161857e-01,  2.47734383e-01,
         -5.39540984e-02],
        [-8.78357217e-02, -3.97457331e-02,  4.26526517e-02,
          1.42784551e-01],
        [-7.87969008e-02, -2.58550137e-01,  4.81251553e-02,
          8.60100389e-02],
        [-1.96612924e-01, -1.28650025e-01, -1.92080364e-01,
         -3.03193051e-02],
        [-4.04486120e-01, -2.34621763e-01, -2.27010533e-01,
         -2.19856858e-01],
        [-3.30344513e-02, -5.21904342e-02, -1.78587109e-01,
          1.78593725e-01],
        [-3.16763461e-01,  9.22997831e-04,  5.38376793e-02,
          1.27701327e-01]],

       [[ 1.86334163e-01, -2.81387597e-01,  4.17697467e-02,
          1.1848

In [7]:
final_memory_state

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[-0.31676346,  0.000923  ,  0.05383768,  0.12770133],
       [-0.03900729,  0.0763637 ,  0.06806298, -0.10032757],
       [ 0.3561219 , -0.2739722 , -0.28882223,  0.19541195],
       [ 0.33215746, -0.27808914, -0.05337242, -0.15615325],
       [-0.29225817, -0.22610791, -0.07072537,  0.07363874],
       [ 0.49882472, -0.5426262 , -0.1087416 ,  0.05401169],
       [ 0.01509258, -0.31284356, -0.387399  ,  0.5169069 ],
       [-0.10448018,  0.20834328, -0.2978293 ,  0.08685686]],
      dtype=float32)>

In [8]:
final_carry_state

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[-0.83064735,  0.00505165,  0.19090933,  0.24255195],
       [-0.10854845,  0.17965795,  0.1444023 , -0.12660423],
       [ 0.59272164, -0.5479315 , -0.6607094 ,  0.4324867 ],
       [ 0.4620272 , -0.3971103 , -0.13281956, -0.19192487],
       [-0.5154136 , -0.42912143, -0.10756049,  0.4725415 ],
       [ 0.7065174 , -1.6615114 , -0.38018626,  0.0762352 ],
       [ 0.03557822, -0.42981708, -0.61394405,  0.9289088 ],
       [-0.21352711,  0.29674482, -0.4496143 ,  0.13109365]],
      dtype=float32)>