In [2]:
import tensorflow as tf
import numpy as np
import shap
import time

In [3]:
x1 = np.array([np.random.randint(0,100) for _ in range(10000)])
x2 = np.array([np.random.randint(0,100) for _ in range(10000)])
x3 = np.array([np.random.randint(0,100) for _ in range(10000)])
y = x1*3 + x2*0.5 + x3*0

In [4]:
input1 = tf.keras.layers.Input(shape=(1,),name="x1")
input2 = tf.keras.layers.Input(shape=(1,),name="x2")
input3 = tf.keras.layers.Input(shape=(1,),name="x3")

concatenate = tf.keras.layers.concatenate(inputs=[input1,input2,input3],axis=-1)
output = tf.keras.layers.Dense(1,activation='relu')(concatenate)

model = tf.keras.models.Model(inputs=[input1,input2,input3],
                              outputs=[output])
model.summary()

model.compile(tf.keras.optimizers.Adam(0.03),
              'mse')

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
x1 (InputLayer)                 [(None, 1)]          0                                            
__________________________________________________________________________________________________
x2 (InputLayer)                 [(None, 1)]          0                                            
__________________________________________________________________________________________________
x3 (InputLayer)                 [(None, 1)]          0                                            
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 3)            0           x1[0][0]                         
                                                                 x2[0][0]                     

In [5]:
history = model.fit({"x1":x1,"x2":x2,"x3":x3},
                    y,
                    batch_size=256,
                    epochs=100
                   )

Epoch 1/100
40/40 [==============================] - 0s 823us/step - loss: 10106.5859
Epoch 2/100
40/40 [==============================] - 0s 729us/step - loss: 3312.2603
Epoch 3/100
40/40 [==============================] - 0s 671us/step - loss: 1608.2889
Epoch 4/100
40/40 [==============================] - 0s 655us/step - loss: 670.7398
Epoch 5/100
40/40 [==============================] - 0s 606us/step - loss: 245.6041
Epoch 6/100
40/40 [==============================] - 0s 617us/step - loss: 78.8262
Epoch 7/100
40/40 [==============================] - 0s 656us/step - loss: 21.8582
Epoch 8/100
40/40 [==============================] - 0s 587us/step - loss: 5.3698
Epoch 9/100
40/40 [==============================] - 0s 631us/step - loss: 1.2304
Epoch 10/100
40/40 [==============================] - 0s 594us/step - loss: 0.3431
Epoch 11/100
40/40 [==============================] - 0s 638us/step - loss: 0.1790
Epoch 12/100
40/40 [==============================] - 0s 637us/step - loss: 0.15

In [10]:
test_x1 = np.array([np.random.randint(0,100) for _ in range(100)])
test_x2 = np.array([np.random.randint(0,100) for _ in range(100)])
test_x3 = np.array([np.random.randint(0,100) for _ in range(100)])
print(test_x1,"\n",test_x2,"\n",test_x3)

[95 65 71 27 94 46 74 63 82 48 31 86 27 64 90 30 99  7 84 97 30 72 38 33
 93  2 53 22 71 69 99 78 91 23 98 83 10  7 41 92 20 70  2 99 91 34 45 22
 99 68 87 16 26 16 18 30 20 10 83  0 70 62 69 87 70  7 93 55 72 38 58 76
  9 25 97 62 36  1 95 32 30 96 79 87 74  7 47 12 27 30 32 97 64 22 73 71
 39 57 28 81] 
 [87 69 41 95 98 51 59 33 19 13 62 53 12 96 57 43 78 45 55 99  9 55 43 59
  0  1 54 46 26 82 62 80  2 68 39 97 39 15 97 70 68 43 79 58 23 62 21 82
 41 93 32 19 34 58 87 33 99 58 90 54 48 59  6 26 40 64 92 59 80 42 10 85
 58 75 92 93 10 47 15 48  9 86 30 77  1 22 62 40 43  2  5 32 65 22 87 62
 72 50 93 64] 
 [69  5  2 89  9  2 42 65 21 61 42 42 69 81 84 42 57 18 39 48 48  4 44 72
 50 64 17 55 85 33 18 21  1 76 24 84 39 73 45 68  2 43 53 49 38  4 78  6
 38 15 19 57 11 66 29 17 61 25 43 83 67 45 68 56 73 10 69 99  3 11 39 94
 48 38 23 65 99 43 88 39  6 61 58 64  9 56 28 93 44 71  5  7 74 29 57 28
 51 40 85 89]


In [16]:
test_predict1 = model.predict([test_x1, test_x2,test_x3])
print(test_predict1.reshape((-1)))

[328.45328  229.51697  233.53026  128.47618  330.98264  163.53914
 251.49582  205.5027   255.52478  150.52425  124.01871  284.4922
  87.032135 239.9592   298.4635   111.529434 335.96274   43.555332
 279.494    340.4579    94.54415  243.52104  135.52373  128.50185
 279.01193    6.555147 186.0249    89.02489  225.99036  247.99156
 327.9938   273.99445  274.0403   103.00042  313.50323  297.4461
  49.5447    28.539616 171.49255  310.96466   94.04487  231.50607
  45.51978  325.97806  284.50772  133.03896  145.51187  107.03393
 317.4935   250.49664  277.0161    57.541588  95.05443   77.015526
  97.52024  106.54922  109.4942    59.042625 293.97354   27.016964
 233.98953  215.50093  210.012    273.99796  229.99036   53.04979
 324.95175  194.47372  256.00824  135.04332  179.03287  270.45074
  56.029915 112.51748  336.97607  232.47119  113.01075   26.54324
 292.48083  120.02736   94.56841  330.9579   251.99924  299.46606
 222.5459    32.045685 172.01768   56.01184  102.52998   91.034615
  98.569

In [19]:
test_predict2 = model.predict({"x1":test_x1,"x2":test_x2,"x3":test_x3})
print(test_predict2.reshape(-1))

[328.45328  229.51697  233.53026  128.47618  330.98264  163.53914
 251.49582  205.5027   255.52478  150.52425  124.01871  284.4922
  87.032135 239.9592   298.4635   111.529434 335.96274   43.555332
 279.494    340.4579    94.54415  243.52104  135.52373  128.50185
 279.01193    6.555147 186.0249    89.02489  225.99036  247.99156
 327.9938   273.99445  274.0403   103.00042  313.50323  297.4461
  49.5447    28.539616 171.49255  310.96466   94.04487  231.50607
  45.51978  325.97806  284.50772  133.03896  145.51187  107.03393
 317.4935   250.49664  277.0161    57.541588  95.05443   77.015526
  97.52024  106.54922  109.4942    59.042625 293.97354   27.016964
 233.98953  215.50093  210.012    273.99796  229.99036   53.04979
 324.95175  194.47372  256.00824  135.04332  179.03287  270.45074
  56.029915 112.51748  336.97607  232.47119  113.01075   26.54324
 292.48083  120.02736   94.56841  330.9579   251.99924  299.46606
 222.5459    32.045685 172.01768   56.01184  102.52998   91.034615
  98.569

# 使用SHAP库 的Kernel Explainer进行特征贡献度的解释

In [31]:
def my_predict(data):
    tem_x1 = data.T[0]
    tem_x2 = data.T[1]
    tem_x3 = data.T[2]
    return model.predict({"x1":tem_x1,"x2":tem_x2,"x3":tem_x3})

In [34]:
test_x_expand = np.expand_dims((test_x1,test_x2,test_x3),axis=0).T.reshape((-1,3))
my_predict(test_x_expand).reshape(-1)

array([328.45328 , 229.51697 , 233.53026 , 128.47618 , 330.98264 ,
       163.53914 , 251.49582 , 205.5027  , 255.52478 , 150.52425 ,
       124.01871 , 284.4922  ,  87.032135, 239.9592  , 298.4635  ,
       111.529434, 335.96274 ,  43.555332, 279.494   , 340.4579  ,
        94.54415 , 243.52104 , 135.52373 , 128.50185 , 279.01193 ,
         6.555147, 186.0249  ,  89.02489 , 225.99036 , 247.99156 ,
       327.9938  , 273.99445 , 274.0403  , 103.00042 , 313.50323 ,
       297.4461  ,  49.5447  ,  28.539616, 171.49255 , 310.96466 ,
        94.04487 , 231.50607 ,  45.51978 , 325.97806 , 284.50772 ,
       133.03896 , 145.51187 , 107.03393 , 317.4935  , 250.49664 ,
       277.0161  ,  57.541588,  95.05443 ,  77.015526,  97.52024 ,
       106.54922 , 109.4942  ,  59.042625, 293.97354 ,  27.016964,
       233.98953 , 215.50093 , 210.012   , 273.99796 , 229.99036 ,
        53.04979 , 324.95175 , 194.47372 , 256.00824 , 135.04332 ,
       179.03287 , 270.45074 ,  56.029915, 112.51748 , 336.976

In [36]:
train_x_expand = np.expand_dims((x1,x2,x3),axis=0)
train_x_expand = train_x_expand.T.reshape((-1,3))
train_x_expand

array([[53, 34, 10],
       [76, 25, 11],
       [22, 75, 27],
       ...,
       [48, 14, 44],
       [49,  7, 74],
       [50, 69,  3]])

In [37]:
explainerKNN =  shap.KernelExplainer(my_predict,train_x_expand)
explainerKNN.expected_value

Using 10000 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.


array([172.93943788])

In [38]:
shap_values_KNN_test = explainerKNN.shap_values(test_x_expand)

In [40]:
sum(shap_values_KNN_test[0][0]) + float(explainerKNN.expected_value)

328.4532775878906

In [39]:
shap_values_KNN_test

[array([[ 1.36865509e+02,  1.86597641e+01, -1.14335354e-02],
        [ 4.68826013e+01,  9.66939339e+00,  2.55352192e-02],
        [ 6.48791843e+01, -4.31562660e+00,  2.72625983e-02],
        [-6.70957621e+01,  2.26554869e+01, -2.29815939e-02],
        [ 1.33866091e+02,  2.41538784e+01,  2.32286609e-02],
        [-1.01065821e+01,  6.79020419e-01,  2.72625688e-02],
        [ 7.38774742e+01,  4.67474624e+00,  4.16076017e-03],
        [ 4.08837288e+01, -8.31135013e+00, -9.11576381e-03],
        [ 9.78729123e+01, -1.53038642e+01,  1.62942619e-02],
        [-4.10772754e+00, -1.83006545e+01, -6.80963468e-03],
        [-5.50980339e+01,  6.17313910e+00,  4.16417426e-03],
        [ 1.09870636e+02,  1.67795221e+00,  4.16095870e-03],
        [-6.70957578e+01, -1.88001152e+01, -1.14299089e-02],
        [ 4.38831685e+01,  2.31549537e+01, -1.83621196e-02],
        [ 1.21868345e+02,  3.67581481e+00, -2.00969937e-02],
        [-5.80974692e+01, -3.31669870e+00,  4.16427736e-03],
        [ 1.48863219e+02